### ISSUE TITLE
ZipApp fixes

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/particle#237]
The ZipApp seems to be broken. We could add a test for it. Here's the current status:

Python 3:
```
 ~/g/s/particle   henryiii/dev  python3 ~/Downloads/particle.pyz search 123                                                                       150ms  Thu Apr  2 22:38:44 2020
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/henryschreiner/Downloads/particle.pyz/__main__.py", line 3, in <module>
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/henryschreiner/Downloads/particle.pyz/particle/__main__.py", line 52, in <module>
  File "/Users/henryschreiner/Downloads/particle.pyz/particle/particle/particle.py", line 801, in from_pdgid
  File "/Users/henryschreiner/Downloads/particle.pyz/particle/particle/particle.py", line 234, in all
  File "/Users/henryschreiner/Downloads/particle.pyz/particle/particle/particle.py", line 391, in load_table
AttributeError: '_io.BytesIO' object has no attribute 'name'
```

Python 2:
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/henryschreiner/Downloads/particle.pyz/__main__.py", line 3, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 182, in run_module
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/Users/henryschreiner/Downloads/particle.pyz/particle/__init__.py", line 13, in <module>
  File "/Users/henryschreiner/Downloads/particle.pyz/particle/geant/__init__.py", line 8, in <module>
  File "/Users/henryschreiner/Downloads/particle.pyz/particle/geant/geant3id.py", line 19, in <module>
  File "/Users/henryschreiner/Downloads/particle.pyz/particle/data/__init__.py", line 9, in <module>
  File "/Users/henryschreiner/Downloads/particle.pyz/importlib_resources/__init__.py", line 5, in <module>
  File "/Users/henryschreiner/Downloads/particle.pyz/importlib_resources/_compat.py", line 8, in <module>
ImportError: No module named pathlib2
```

I think this last issue is one that came up with newer versions of `importlib_resources` - we need to install pathlib2 now in the zipapp. The Python3 error seems to have come from a recent change where the datafile is being treated as an actual file - there is no promise in Python that files really will exist as a text file on a disk - when you are in a zip file, this is an example of a case where they are not real files.

**Comment by eduardo-rodrigues** [comment]
Thanks for reporting. We can also consider getting rid of this if things get out of control or too complicated to maintain. In the end I have no idea who is using the ZipApp functionality.
